/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visual.TelasLocacao;

import arquivo.Arquivo;
import entidades.Cliente;
import entidades.Locacao;
import java.io.File;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import servicos.GerenciadorClientes;
import servicos.GerenciadorLocacoes;

/**
 *
 * @author Marcelo Arrojo, Matheus Davila, Mateus Balda e João Paulo Merlugo
 * @since 1.0
 */
public class TelaPesquisarLocacao extends javax.swing.JInternalFrame {

    private Locacao locacao;
    /**
     * Creates new form TelaPesquisarLocacao
     */
    public TelaPesquisarLocacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPesquisar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons 1/zoom.png"))); // NOI18N
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Listar todos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton2))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cliente", "Veiculo", "Seguro", "Valor Diária", "Data Inicial", "Data Final"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        carregarLocacoes();
        DefaultTableModel dtmLocacao = (DefaultTableModel) jTable1.getModel();
        int codLocacao;

        codLocacao = Integer.parseInt(txtPesquisar.getText());
        try {
            locacao = GerenciadorLocacoes.INSTANCE.get(codLocacao);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        codLocacao = locacao.getCodLocacao();
        String cliente = locacao.getCliente().getNome();
        String veiculo = locacao.getVeiculo().getPlaca();
        boolean seguro = locacao.isSeguro();
        double valorDiario = locacao.getValorDiaria();
        Date dataInicial = locacao.getDataInicial();
        Date dataFinal = locacao.getDataFinal();

        Object[] data = {codLocacao, cliente, veiculo, seguro, valorDiario, dataInicial, dataFinal};

        dtmLocacao.addRow(data);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        carregarLocacoes();
        DefaultTableModel dtmLocacoes = (DefaultTableModel)jTable1.getModel();
        for (int i = 0; i < GerenciadorLocacoes.INSTANCE.size(); i++){
            int codLocacao = GerenciadorLocacoes.INSTANCE.getTodosLocacoes().get(i).getCodLocacao();
            String cliente = GerenciadorLocacoes.INSTANCE.getTodosLocacoes().get(i).getCliente().getNome();
            String veiculo = GerenciadorLocacoes.INSTANCE.getTodosLocacoes().get(i).getVeiculo().getPlaca();
            boolean seguro = GerenciadorLocacoes.INSTANCE.getTodosLocacoes().get(i).isSeguro();
            double valorDiario = GerenciadorLocacoes.INSTANCE.getTodosLocacoes().get(i).getValorDiaria();
            Date dataInicial = GerenciadorLocacoes.INSTANCE.getTodosLocacoes().get(i).getDataInicial();
            Date dataFinal = GerenciadorLocacoes.INSTANCE.getTodosLocacoes().get(i).getDataFinal();
            
            Object[] data = {codLocacao, cliente, veiculo, seguro, valorDiario, dataInicial, dataFinal};

            dtmLocacoes.addRow(data);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public void carregarLocacoes(){
           if (new File("locacoes.bin").exists()){
              try {
                  GerenciadorLocacoes.INSTANCE = (GerenciadorLocacoes) Arquivo.ler("locacoes.bin");
              }catch (Exception e){
                  System.err.println(e.getMessage());
              }
          }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
