/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visual.telasVeiculo;

import arquivo.Arquivo;
import entidades.Caminhao;
import entidades.Carro;
import entidades.Categoria;
import entidades.Onibus;
import entidades.Veiculo;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import servicos.GerenciadorVeiculos;
import excecoes.ExcecaoCarro;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Marcelo Arrojo, Matheus Davila, Mateus Balda e João Paulo Merlugo
 * @since 1.0
 */
public class TelaPesquisarVeiculo extends javax.swing.JInternalFrame {

    private Veiculo veiculo;
    /**
     * Creates new form TelaPesquisarVeiculo
     */
    public TelaPesquisarVeiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPesquisar = new javax.swing.JTextField();
        jButtonPesquisarVeiculo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jButtonPesquisarVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons 1/zoom.png"))); // NOI18N
        jButtonPesquisarVeiculo.setText("Pesquisar");
        jButtonPesquisarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarVeiculoActionPerformed(evt);
            }
        });

        jButton2.setText("Listar todos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisarVeiculo))
                    .addComponent(jButton2))
                .addContainerGap(392, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton2))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Ano", "Valor Diária", "Número de Passageiros", "Ar-Condicionado", "Número de Portas", "Média de KM por Litro", "Categoria", "Serviço de Internet", "Número de Eixos", "Carga Máxima"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarVeiculoActionPerformed
        // TODO add your handling code here:
        carregarVeiculos();
        String placa, servicoInternet = null;
        Categoria categoria = null;
        int numPassageiros = 0, numPortas = 0, mediaKMLitro = 0, numEixos = 0, cargaMax = 0;
        boolean arCondicionado = false ;
        DefaultTableModel dtmVeiculo = (DefaultTableModel)jTable1.getModel();
        String placaPesquisar;

        placaPesquisar = txtPesquisar.getText();
        try {
            veiculo = GerenciadorVeiculos.INSTANCE.get(placaPesquisar);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
            if(veiculo instanceof Caminhao) {
                Caminhao caminhao = (Caminhao) veiculo; 
                numEixos = caminhao.getNumEixos();
                cargaMax = caminhao.getCargaMax();
            }else if(veiculo instanceof Carro){
                Carro carro = (Carro) veiculo;
                numPassageiros = carro.getNumPassageiros();  
                numPortas = carro.getNumPortas();
                mediaKMLitro = carro.getMediaKMLitro();
                arCondicionado = carro.isArCondicionado();
            }else if(veiculo instanceof Onibus){
                Onibus onibus = (Onibus) veiculo;
                numPassageiros = onibus.getNumPassageiros();
                arCondicionado = onibus.isArCondicionado();
                categoria = onibus.getCategoria();
                servicoInternet = ExcecaoCarro.booleanToString(onibus.isServicoInternet());
            }
                
            placa = veiculo.getPlaca();
            int ano = veiculo.getAno();
            double valorDiaria = veiculo.getValorDiaria();
            
            
            Object[] data = {placa, ano, valorDiaria, numPassageiros, arCondicionado, numPortas, mediaKMLitro, categoria, servicoInternet, numEixos, cargaMax};

            dtmVeiculo.addRow(data);
    }//GEN-LAST:event_jButtonPesquisarVeiculoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        carregarVeiculos();
        DefaultTableModel dtmVeiculo = (DefaultTableModel)jTable1.getModel();
        try {
            for (int i = 0; i < GerenciadorVeiculos.INSTANCE.size(); i++){
                Categoria categoria = null;
                String placa;
                int numPassageiros = 0, numPortas = 0, mediaKMLitro = 0, numEixos = 0, cargaMax = 0;
                boolean arCondicionado = false, servicoInternet = false;
                Veiculo veiculo = (Veiculo) GerenciadorVeiculos.INSTANCE.getTodosVeiculos().get(i);
                if(veiculo instanceof Caminhao) {
                    Caminhao caminhao = (Caminhao) veiculo;
                    numEixos = caminhao.getNumEixos();
                    cargaMax = caminhao.getCargaMax();
                }else if(veiculo instanceof Carro){
                    Carro carro = (Carro) veiculo;
                    numPassageiros = carro.getNumPassageiros();
                    numPortas = carro.getNumPortas();
                    mediaKMLitro = carro.getMediaKMLitro();
                    arCondicionado = carro.isArCondicionado();
                }else if(veiculo instanceof Onibus){
                    Onibus onibus = (Onibus) veiculo;
                    numPassageiros = onibus.getNumPassageiros();
                    arCondicionado = onibus.isArCondicionado();
                    categoria = onibus.getCategoria();
                    servicoInternet = onibus.isServicoInternet();
                }
                
                placa = veiculo.getPlaca();
                int ano = veiculo.getAno();
                double valorDiaria = veiculo.getValorDiaria();
                
                
                Object[] data = {placa, ano, valorDiaria, numPassageiros, arCondicionado, numPortas, mediaKMLitro, categoria, servicoInternet, numEixos, cargaMax};
                
                dtmVeiculo.addRow(data);
                
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void carregarVeiculos(){
           if (new File("veiculos.bin").exists()){
              try {
                  GerenciadorVeiculos.INSTANCE = (GerenciadorVeiculos) Arquivo.ler("veiculos.bin");
              }catch (Exception e){
                  System.err.println(e.getMessage());
              }
          }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonPesquisarVeiculo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
